service: serverless-fastapi
frameworkVersion: '3'


provider:
    name: aws
    runtime: python3.9

functions:
    api:
        handler: app.handler
        events:
            - httpApi: "*"

custom:
    apiKeys:
        - name: test-keys
        - name: prod-keys

plugins:
    - serverless-python-requirements
    - serverless-add-api-key